model:  ["GCN"]
batch_size: [32]
emb_dim: [300]
drop_out: [0, 0.5]
num_layers: [5]
num_mlp_layers: [2]
pooling: ["mean"]
lr: [0.001]
lr2: [0.0005]
freeze_gnn: [0]
epochs: [100]
lr_schedule_patience: [101]
drop_feat: [1]